CREATE TABLE "evenements" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"titre" text NOT NULL,
	"description_courte" text,
	"description_complete" jsonb DEFAULT '[]'::jsonb,
	"programme" jsonb DEFAULT '[]'::jsonb,
	"image" text,
	"image_alt" text,
	"image_credit" text,
	"debut_le" timestamp,
	"fin_le" timestamp,
	"journee_entiere" boolean DEFAULT false NOT NULL,
	"lieu" text,
	"adresse" text,
	"code_postal" text,
	"commune" text,
	"lien_carte" text,
	"url_inscription" text,
	"appel_action" text,
	"partenaires" jsonb DEFAULT '[]'::jsonb,
	"documents" jsonb DEFAULT '[]'::jsonb,
	"annule" boolean DEFAULT false NOT NULL,
	"motif_annulation" text,
	"statut" text DEFAULT 'brouillon' NOT NULL,
	"date_publication" timestamp,
	"mise_en_avant" boolean DEFAULT false NOT NULL,
	"sur_accueil" boolean DEFAULT false NOT NULL,
	"seo" jsonb DEFAULT '{}'::jsonb,
	"auteur_id" text,
	"modifie_par_id" text,
	"version" integer DEFAULT 1 NOT NULL,
	"cree_le" timestamp DEFAULT now() NOT NULL,
	"maj_le" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "evenements_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "evenements" ADD CONSTRAINT "evenements_auteur_id_user_id_fk" FOREIGN KEY ("auteur_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evenements" ADD CONSTRAINT "evenements_modifie_par_id_user_id_fk" FOREIGN KEY ("modifie_par_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;